config/routes.rb
Rails.application.routes.draw do
  get 'blogs/title:string'

  get 'blogs/body:text'

  resources :waffles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/waffle.rb
class Waffle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def title:string
  end

  def body:text
  end
end

app/controllers/waffles_controller.rb
class WafflesController < ApplicationController
  before_action :set_waffle, only: [:show, :edit, :update, :destroy]

  # GET /waffles
  # GET /waffles.json
  def index
    @waffles = Waffle.all
  end

  # GET /waffles/1
  # GET /waffles/1.json
  def show
  end

  # GET /waffles/new
  def new
    @waffle = Waffle.new
  end

  # GET /waffles/1/edit
  def edit
  end

  # POST /waffles
  # POST /waffles.json
  def create
    @waffle = Waffle.new(waffle_params)

    respond_to do |format|
      if @waffle.save
        format.html { redirect_to @waffle, notice: 'Waffle was successfully created.' }
        format.json { render :show, status: :created, location: @waffle }
      else
        format.html { render :new }
        format.json { render json: @waffle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waffles/1
  # PATCH/PUT /waffles/1.json
  def update
    respond_to do |format|
      if @waffle.update(waffle_params)
        format.html { redirect_to @waffle, notice: 'Waffle was successfully updated.' }
        format.json { render :show, status: :ok, location: @waffle }
      else
        format.html { render :edit }
        format.json { render json: @waffle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waffles/1
  # DELETE /waffles/1.json
  def destroy
    @waffle.destroy
    respond_to do |format|
      format.html { redirect_to waffles_url, notice: 'Waffle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waffle
      @waffle = Waffle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waffle_params
      params.require(:waffle).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/waffles_helper.rb
module WafflesHelper
end

app/views/blogs/body:text.html.erb
<h1>Blogs#body:text</h1>
<p>Find me in app/views/blogs/body:text.html.erb</p>

app/views/blogs/title:string.html.erb
<h1>Blogs#title:string</h1>
<p>Find me in app/views/blogs/title:string.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/waffles/_form.html.erb
<%= form_with(model: waffle, local: true) do |form| %>
  <% if waffle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(waffle.errors.count, "error") %> prohibited this waffle from being saved:</h2>

      <ul>
      <% waffle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :waffle_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/waffles/edit.html.erb
<h1>Editing Waffle</h1>

<%= render 'form', waffle: @waffle %>

<%= link_to 'Show', @waffle %> |
<%= link_to 'Back', waffles_path %>

app/views/waffles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Waffles</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waffles.each do |waffle| %>
      <tr>
        <td><%= waffle.body %></td>
        <td><%= link_to 'Show', waffle %></td>
        <td><%= link_to 'Edit', edit_waffle_path(waffle) %></td>
        <td><%= link_to 'Destroy', waffle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waffle', new_waffle_path %>

app/views/waffles/new.html.erb
<h1>New Waffle</h1>

<%= render 'form', waffle: @waffle %>

<%= link_to 'Back', waffles_path %>

app/views/waffles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @waffle.body %>
</p>

<%= link_to 'Edit', edit_waffle_path(@waffle) %> |
<%= link_to 'Back', waffles_path %>